[package]
name = "prom-ui-backend-native"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["prom-ui-runtime/std"]
winit-backend = ["std", "dep:winit"]
wgpu-backend = ["std", "dep:wgpu", "dep:pollster", "dep:bytemuck"]

[dependencies]
prom-ui = { path = "../prom-ui", default-features = false }
prom-ui-runtime = { path = "../prom-ui-runtime", default-features = false }
winit = { version = "0.30.13", optional = true, default-features = false, features = ["rwh_06"] }
wgpu = { version = "0.20", optional = true, default-features = false, features = ["wgsl"] }
pollster = { version = "0.3", optional = true }
bytemuck = { version = "1.15", optional = true, features = ["derive"] }
