[package]
name = "sm-emit"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["sm-ir/std", "sm-format/std"]

[dependencies]
sm-format = { path = "../sm-format", default-features = false, features = ["std"] }
sm-ir = { path = "../sm-ir", default-features = false, features = ["std", "profile-rust", "profile-logos", "debug-symbols"] }
