use prom_ui::lowering::{lower_ast_to_ir, UiLoweringConfig};
use prom_ui::model::{UiNode, UiNodeId, UiNodeKind, UiNodeResolution, UiTree, UiTreeId};
use prom_ui::projection::project_ir_to_projection;
use prom_ui::renderer::{render_projection_to_model, UiRenderModel, UiRenderNodeKind};
use prom_ui::tree_to_ast;

fn build_mixed_tree_render_model(tree_id_raw: u64) -> UiRenderModel {
    let mut tree = UiTree::new(UiTreeId::new(tree_id_raw));

    // Root
    let mut root = UiNode::new(UiNodeId::new(1), UiNodeKind::Root);
    root.push_child(UiNodeId::new(2));
    root.push_child(UiNodeId::new(3));
    tree.push_node(root);

    // Element
    let mut element = UiNode::new(UiNodeId::new(2), UiNodeKind::Element);
    element.set_parent(Some(UiNodeId::new(1)));
    element.push_child(UiNodeId::new(4));
    tree.push_node(element);

    // Text inside Element
    let mut text = UiNode::new(UiNodeId::new(4), UiNodeKind::Text);
    text.set_parent(Some(UiNodeId::new(2)));
    tree.push_node(text);

    // Slot (sibling to Element)
    let mut slot =
        UiNode::with_resolution(UiNodeId::new(3), UiNodeKind::Slot, UiNodeResolution::Known);
    slot.set_parent(Some(UiNodeId::new(1)));
    tree.push_node(slot);

    let ast = tree_to_ast(&tree).unwrap();
    let ir = lower_ast_to_ir(&ast, &UiLoweringConfig::default()).unwrap();
    let projection = project_ir_to_projection(&ir).unwrap();
    render_projection_to_model(&projection).unwrap()
}

#[test]
fn render_model_mixed_nodes_generation_is_stable_and_deterministic() {
    let base_model = build_mixed_tree_render_model(100);

    // 1. Repeated runs do not change the result
    for _ in 0..10 {
        let repeated_model = build_mixed_tree_render_model(100);
        assert_eq!(base_model, repeated_model);
    }

    // 2. Node order is stable and predictable (Root -> Element -> Slot -> Text)
    // The exact order depends on how tree_to_ast and subsequent lowering visits children.
    // Assuming standard pre-order or insertion-order propagation, the order of insertion:
    // Root (1), Element (2), Text (4), Slot (3)
    let nodes = base_model.nodes();
    assert_eq!(nodes.len(), 4);

    let node_kinds: Vec<UiRenderNodeKind> = nodes.iter().map(|n| n.kind()).collect();

    // We expect the exact order of nodes generated by the lowering process to remain
    // absolutely stable across all identical runs.
    let expected_kinds = vec![
        UiRenderNodeKind::Root,
        UiRenderNodeKind::Element,
        UiRenderNodeKind::Text,
        UiRenderNodeKind::Fragment, // Slot lowers to Fragment with no markers
    ];

    assert_eq!(node_kinds, expected_kinds);

    // 3. Source links are stable
    for node in nodes {
        assert!(node.source_ir_node().is_some());
    }
}
