[package]
name = "sm-verify"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["sm-runtime-core/std"]

[dependencies]

sm-runtime-core = { path = "../sm-runtime-core", default-features = false, features = ["std"] }
sm-format = { path = "../sm-format", default-features = false, features = ["std"] }

[dev-dependencies]

sm-ir = { path = "../sm-ir", default-features = false, features = ["std"] }
